name: DragonEvent
version: '${project.version}'
main: cz.lisacek.dragonevent.DragonEvent
api-version: 1.13
authors: [lisacekmore]
commands:
  dragonevent:
    aliases:
      - de
  vote:
  votetop:
  offlinewards:
    aliases:
      - ow
      - claimoffline
      - claimoff
